### ISSUE TITLE
Missing link to pre-trained models

### ISSUE THREAD

**Issue by kegro** [ESA-PhiLab/NGVEO#3]
In the README you write 'In addition we pre-trained models for tree-height estimation and forest-cover estimation can be dowloaded at LINK HERE'. The link is missing :). Can you please provide the link to the models?

Also, any additional information on the training of these models is greatly appreciated.

**Comment by waldeland** [comment]
Thank you for your feedback. I have added the links now. Please note that the models where trained with data from the Liwale region in Tanzania, and may not necessarily be accurate far away from this region.

I will try to add some more information on the training later on.
