### ISSUE TITLE
Trouble installing all packages without errors

### ISSUE THREAD

**Issue by rkochev** [ESA-PhiLab/NGVEO#5]
Can you please tell us which version on Python is used?

I tried 3.6.10 in both Linux and Windows and still get a lot of errors. 
Ultimately i was able to fix them all by installing newer version of packages, but still...

Also prepare_data.py took almost 6 hours, and starting with ~30GB of data it produces more than 200GB of data, before giving an error that Sentinel 3 is not supported.

Possibly if you can tell us how to train on GPU would be great.

**Comment by waldeland** [comment]
Hi,
We used python 3.5.2. 

As for the data size, that depends on how many scenes you want to include. Sentinel-3 is not supported - only Sentinel 2.
Did you use the example scenes provided in the example_l*.txt - files? I recomend to start with these.

Training on GPU should be straight forward by running train.py
